name: Deploy .NET Core app to Azure Web App

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez déployer

env:
  AZURE_WEBAPP_NAME: 'P2-API'  # Remplacez par le nom de votre App Service
  AZURE_WEBAPP_PACKAGE_PATH: 'publish_output'  # Dossier de sortie de la publication
  DOTNET_VERSION: '8.0.401'  # Version de .NET utilisée dans votre projet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
